"""Esquema canónico para exportaciones de eventos."""

from __future__ import annotations

EVENTOS_PLACEHOLDER = "-"

EVENTOS_HEADER_PREFIX = [
    "case_id",
    "tipo_informe",
    "categoria_1",
    "categoria_2",
    "modalidad",
    "tipo_de_producto",
    "canal",
    "proceso_impactado",
    "product_id",
    "cod_operation",
    "monto_investigado",
    "tipo_moneda",
    "tipo_id_cliente_involucrado",
    "client_id_involucrado",
    "flag_cliente_involucrado",
    "nombres_cliente_involucrado",
    "apellidos_cliente_involucrado",
    "matricula_colaborador_involucrado",
    "apellido_paterno_involucrado",
    "apellido_materno_involucrado",
    "nombres_involucrado",
    "division",
    "area",
    "servicio",
    "nombre_agencia",
    "codigo_agencia",
    "puesto",
    "fecha_cese",
    "tipo_de_falta",
    "tipo_sancion",
    "fecha_ocurrencia",
    "fecha_descubrimiento",
    "monto_fraude_interno_soles",
    "monto_fraude_interno_dolares",
    "monto_fraude_externo_soles",
    "monto_fraude_externo_dolares",
    "monto_falla_en_proceso_soles",
    "monto_falla_en_proceso_dolares",
    "monto_contingencia_soles",
    "monto_contingencia_dolares",
    "monto_recuperado_soles",
    "monto_recuperado_dolares",
    "monto_pagado_soles",
    "monto_pagado_dolares",
    "comentario_breve",
    "comentario_amplio",
    "id_reclamo",
    "nombre_analitica",
    "codigo_analitica",
    "telefonos_cliente_relacionado",
    "correos_cliente_relacionado",
    "direcciones_cliente_relacionado",
    "accionado_cliente_relacionado",
]

EVENTOS_LEGACY_FIELDS = [
    "id_caso",
    "tipo_informe",
    "categoria1",
    "categoria2",
    "modalidad",
    "canal",
    "proceso",
    "fecha_de_ocurrencia",
    "fecha_de_descubrimiento",
    "centro_costos",
    "matricula_investigador",
    "investigador_nombre",
    "investigador_cargo",
    "comentario_breve",
    "comentario_amplio",
    "id_producto",
    "id_cliente",
    "id_colaborador",
    "id_cliente_involucrado",
    "tipo_involucrado",
    "id_reclamo",
    "fecha_ocurrencia",
    "fecha_descubrimiento",
    "tipo_producto",
    "tipo_moneda",
    "monto_investigado",
    "monto_perdida_fraude",
    "monto_falla_procesos",
    "monto_contingencia",
    "monto_recuperado",
    "monto_pago_deuda",
    "nombre_analitica",
    "codigo_analitica",
    "cliente_nombres",
    "cliente_apellidos",
    "cliente_tipo_id",
    "cliente_flag",
    "cliente_telefonos",
    "cliente_correos",
    "cliente_direcciones",
    "cliente_accionado",
    "colaborador_flag",
    "colaborador_nombres",
    "colaborador_apellidos",
    "colaborador_division",
    "colaborador_area",
    "colaborador_servicio",
    "colaborador_puesto",
    "colaborador_fecha_carta_inmediatez",
    "colaborador_fecha_carta_renuncia",
    "colaborador_nombre_agencia",
    "colaborador_codigo_agencia",
    "colaborador_tipo_falta",
    "colaborador_tipo_sancion",
    "monto_asignado",
]

EVENTOS_HEADER = EVENTOS_HEADER_PREFIX + [
    field for field in EVENTOS_LEGACY_FIELDS if field not in EVENTOS_HEADER_PREFIX
]

__all__ = [
    "EVENTOS_HEADER",
    "EVENTOS_HEADER_PREFIX",
    "EVENTOS_LEGACY_FIELDS",
    "EVENTOS_PLACEHOLDER",
]
